### ISSUE TITLE
Amount Problem

### ISSUE THREAD

**Issue by Roxsilver** [SirFreddie/fred_store#1]
I tried to set up peaches x1, x5, x10 but somehow its not working i brought everytime just one item
but i changed the Cantidad amount too so it should work can you look at it maybe i like the fred_store script :D

**Comment by SirFreddie** [comment]
Sorry for the late respones. It depends on what you are trying to do, as far as i can see, Cantidad do not affect the quantity of items you buy, just the ammount you want to sell.
The script is quite old and outdated tho, i have not been working on RedM scripts in a while.
